version: '3.9'

services:
  server1:
    container_name: nodejs-cicd:latest
    restart: on-failure
    build: .
    ports:
      - '3001:3000'
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - server1