# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.2

jobs:
  build-and-test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build-and-push:
    # push docker images to docker hub
    environment:
      DOCKER_IMAGE: duyhoangptit/nodejs-cicd
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  # ...previous job(s)...
  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
          # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  # name workflow
  my-nodejs-cicd:
    jobs:
      - build-and-test
      - build-and-push:
          # chi duoc push khi nao da pass qua test
          requires:
            - build-and-test # only deploy if the build-and-test job has completed
          filters:
            branches:
              only: master # only deploy when on master
      - deploy:
          # chi duoc push khi 
          requires:
            - build-and-test # only deploy if the build-and-test job has completed
          filters:
            branches:
              only: master # only deploy when on master