# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@1.4.0

jobs:
  build-and-test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build-and-push-docker-hub:
    environment:
      DOCKER_IMAGE: duyhoangptit/nodejs-cicd
      DOCKER_TAG: latest
    # push docker images to docker hub duyhoangptit/nodejs-cicd
    executor: docker/docker
    steps:
      - run: echo $DOCKER_IMAGE_CONF
      - run: echo $DOCKER_TAG_CONF
      - setup_remote_docker
      - checkout
      # login
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      # docker build images
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      # docker push images to docker hub
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy-heroku: # this can be any name you choose
    # https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
    # Lay token tu heroku: HEROKU_API_KEY
    # Create project in heroku: HEROKU_APP_NAME
    # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  # name workflow
  my-nodejs-cicd:
    jobs:
      - build-and-test
      - build-and-push-docker-hub:
          # chi duoc push khi nao da pass qua test
          requires:
            - build-and-test # only deploy if the build-and-test job has completed
          filters:
            branches:
              only: master # only deploy when on master
      - deploy-heroku:
          # chi duoc deploy khi run test pass
          requires:
            - build-and-test # only deploy if the build-and-test job has completed
          filters:
            branches:
              only: master # only deploy when on master